web/TamoMessenger/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TamoMessenger.views.home', name='home'),
    # url(r'^TamoMessenger/', include('TamoMessenger.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'', include('messenger.urls', namespace='messenger')),
)

web/messenger/urls.py
from django.conf.urls import patterns, url, include

user_urlpatterns = patterns('messenger.user',
    url(r'^$', 'index', name='index'),
    url(r'^naujas-tamo-vartotojas/$', 'add_tamo', name='add_tamo'),
    url(r'^tamo-vartotojas/$', 'tamo', name='tamo'),
    url(r'^trinti-tamo-vartotoja/$', 'delete_tamo', name='delete_tamo'),
    url(r'^funkcijos/$', 'functions', name='functions'),
    url(r'^atsijungti/$', 'logout', name='logout')
)

urlpatterns = patterns('messenger.views',
    url(r'^$', 'login', name='index'),
    url(r'^registracija/$', 'registration', name='registration'),
    url(r'^vartotojas/', include(user_urlpatterns, namespace='user'))
)

web/messenger/models.py
#coding=utf8

from django.db import models
from django.contrib.auth.models import User

class TamoUser(models.Model):
    user = models.ForeignKey(User, primary_key=True)
    username = models.CharField('Vartotojo vardas', max_length=30, unique=True, blank=False,
                                error_messages={'unique': 'Toks TAMO vartotojas jau naudojamas'})
    password = models.CharField(u'Slaptažodis', max_length=254, blank=False)
    phone = models.CharField('Telefono numeris', max_length=12, unique=True, blank=False,
                             error_messages={'unique': 'Toks telefono numeris jau naudojamas'})
    send_grades = models.BooleanField(u'Pažymiai', default=True)
    send_tests = models.BooleanField('Atsiskaitomieji darbai', default=False)

web/messenger/views.py
#coding=utf8

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login as login_user
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from web_forms import RegistrationForm, LoginForm

def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')

            #Create new user
            User.objects.create_user(username, email, password)

            messages.add_message(request, messages.SUCCESS, u'Vartotojas buvo sėkmingai sukurtas.\
             <a href="%s">Prisijungti</a>' % reverse('messenger:index'))
    else:
        form = RegistrationForm()

    return render(request, 'messenger/registration.html', {'title': 'Registracija',
                                                           'form': form})

def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('messenger:user:index'))

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            login_user(request, user)

            return HttpResponseRedirect(reverse('messenger:user:index'))
    else:
        form = LoginForm()

    return render(request, 'messenger/login.html', {'title': 'Prisijungimas',
                                                    'form': form})

web/messenger/templates/messenger/login.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}

    <form method="POST" action=""> {% csrf_token %}
        {{ form.username }}
        {{ form.password }}

        <div class='link'><a href='{% url "messenger:registration" %}'>Dar neturite vartotojo?</a></div>

        <button class="btn btn-large btn-primary" type="submit">Jungtis</button>
    </form>
{% endblock container %}

web/messenger/templates/messenger/registration.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}

    <form method="POST" action=""> {% csrf_token %}
        {% include "flash_messages.html" %}

        {{ form.username }}
        {{ form.password }}
        {{ form.repeat_password }}
        {{ form.email }}

        <div class='link'><a href='{% url "messenger:index" %}'>Jau turite vartotoją?</a></div>

        <button class="btn btn-large btn-primary" type="submit">Registruotis</button>
    </form>
{% endblock container %}

web/messenger/templates/messenger/user/functions.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}

    <form method="POST" action=""> {% csrf_token %}
        {% include "flash_messages.html" %}

        {{ form.send_grades.label }}
        {{ form.send_grades }}<br />

        {{ form.send_tests.label }}
        {{ form.send_tests }}<br /><br />

        <button class="btn btn-large btn-primary" type="submit">Keisti</button>
        <a href="#explanation" role="button" class="btn btn-large btn-info" data-toggle="modal">Paaiškinimas</a>

        <div id="explanation" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="explanation" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Funkcijų paaiškinimas</h3>
            </div>
            <div class="modal-body">
                <h4>Pažymiai</h4>
                <p>
                    Pasirinkę šią funkciją Jūs turėsite galimybę gauti naujausius pažymius tiesiai į savo telefoną.
                    Kai naujas pažymys atsiras Jūsų TAMO vartotojo duomenų bazėje, jis nedelsiant bus išsiųstas SMS žinute
                    nurodytu numeriu.
                </p>
                <h4>Atsiskaitomieji darbai</h4>
                <p>
                    Pasirinkitę šią funkciją, likus vienai dienai iki atsiskaitomojo darbo, apie jį bus pranešta SMS žinute. Todėl
                    daugiau nepraleisite atsiskaitomųjų darbų ir spėsite jiems reikiamai pasiruošti.
                </p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Uždaryti</button>
            </div>
        </div>
    </form>
{% endblock container %}

web/messenger/templates/messenger/user/index.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}
{% endblock container %}

web/messenger/templates/messenger/user/navigation.html
{% if user.is_authenticated %}
    <ul class="nav nav-tabs nav-stacked user-navigation">
        <li><a href="{% url "messenger:user:index" %}">Pagrindinis</a></li>
        <li><a href="{% url "messenger:user:tamo" %}">Tamo vartotojas</a></li>
        <li><a href="{% url "messenger:user:functions" %}">Funkcijos</a></li>
        <li><a href="#">Nustatymai</a></li>
        <li><a href="{% url "messenger:user:logout" %}">Atsijungti</a></li>
    </ul>
{% endif %}

web/messenger/templates/messenger/user/tamo_account.html
{% extends "base.html" %}

{% block container %}
    {{ block.super }}

    <form method="POST" action=""> {% csrf_token %}
        {% include "flash_messages.html" %}

        {{ form.username }}
        {{ form.password }}
        {{ form.phone }}

        {% if action == 'add' %}
            <button class="btn btn-large btn-primary" type="submit">Pridėti</button>
        {% else %}
            <button class="btn btn-large btn-primary" type="submit">Keisti</button>
            <a href="{% url "messenger:user:delete_tamo" %}"><div class="btn btn-large btn-danger">Trinti</div></a>
        {% endif %}
    </form>
{% endblock container %}

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
        {% load staticfiles %}

		<meta charset="UTF-8">
		<title>Tamo pranešėjas - {{ title }}</title>

		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href="{% static "messenger/css/bootstrap.css" %}">
	    <link rel="stylesheet" type="text/css" href="{% static "messenger/css/styles.css" %}">
    </head>
	<body>
		<div class="container">
            <h1>Tamo pranešėjas</h1>

            {% include "messenger/user/navigation.html" %}

            <div class="main">
                {% block container %}
                    <h3 class="heading">{{ title }}</h3>

                    {% if form %}
                        {% include "form_errors.html" %}
                    {% endif %}
                {% endblock %}
            </div>
		</div>

		<!-- Javascript -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="{% static "messenger/js/bootstrap.js" %}"></script>
	</body>
</html>

web/templates/flash_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>{{ message|safe }}</strong>
        </div>
    {% endfor %}
{% endif %}

web/templates/form_errors.html
{% if form.errors or form.non_field_errors %}
    <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Klaida!<br /><br />

            {% if form.errors %}
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.label }}
                        <ul class='errorlist'>
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% if form.non_field_errors %}
                {{ form.non_field_errors }}
            {% endif %}
    </div>
{% endif %}